[aws]
style = 'bold #ffb86c'

[character]
error_symbol = '[Î»](bold #df5b61)'
success_symbol = '[Î»](bold  #87c7a1)'

[cmd_duration]
style = 'bold #f1fa8c'

[directory]
style = 'bold #96d6b0'

[package]
symbol = 'ó°— '
style = 'bold #96d6b0'

[kotlin]
symbol = 'ó±ˆ™ '
style = 'bold #cb92f2'

[java]
symbol = 'îœ¸ '
style = 'bold #ee6a70'

[golang]
symbol = 'ó°Ÿ“ '
style = 'bold #7ba5dd'

[lua]
symbol = 'î˜  '
style = 'bold #cb92f2'

[c]
symbol = 'î˜ '
style = 'bold #7fc8db'

[python]
symbol = 'îœ¼ '
style = 'bold #7ba5dd'

[nodejs]
symbol = 'ó°Œ '
style = 'bold #de8f78'

[php]
symbol = 'î˜ˆ '
style = 'bold #7ba5dd'

[haskell]
symbol = 'î· '
style = 'bold #96d6b0'

[git_branch]
symbol = 'îœ‚ '
style = 'bold #de8f78'

[git_status]
style = 'bold #de8f78'

[git_commit]
style = 'bold #de8f78'

[docker_context]
symbol = 'ó°¡¨ '
style = 'bold #7ba5dd'

[gcloud]
symbol = 'ó±‡¶ '
style = 'bold #de8f78'

[nix_shell]
symbol = 'ó±„… '
style = 'bold #7ba5dd'

[hostname]
style = 'bold #bd93f9'

[os.symbols]
Alpaquita = "ğŸ”” "
Alpine = "ïŒ€ "
Amazon = "ğŸ™‚ "
Android = "ó°€² "
Arch = "ó°£‡ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "î½ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒŠ "
FreeBSD = "ó°£  "
Garuda = "ğŸ¦… "
Gentoo = "ïŒ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Linux = "îœ’ "
Mabox = "ğŸ“¦ "
Macos = "îœ‘ "
Manjaro = "ïŒ’ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ó°£­ "
NetBSD = "ğŸš© "
NixOS = "ïŒ“ "
OpenBSD = "ïŒ¨ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ïŒ” "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ–  "
Redox = "ğŸ§ª "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ïŒœ "
Unknown = "ï„¨ "
Windows = "ó°¨¡ "

[battery]
full_symbol = 'ï‰€ '
charging_symbol = 'ï‰€ '
discharging_symbol = 'ï‰ '
unknown_symbol = 'ï‰„ '
empty_symbol = 'ï‰„ '

[username]
format = '[$user]($style) on '
style_user = 'bold #8be9fd'
